### ISSUE TITLE
Fake Testing Data 

### ISSUE THREAD

**Issue by EricLiu750501** [YCNeo/Cloud-Native-Final#29]
密碼加密過似乎和 fake testing data 不太一樣

import SHA256 from 'crypto-js/sha256';

password1 -> 0b14d501a594442a01c6859541bcb3e8164d183d32937b851835442f69d5c94e
但是 sql 上的是 c2b7e8d7a4c236b06b9ab7d1ad2d2f0c16e0590da4d6e5fb10f194b48e59bf4a

**Comment by YCNeo** [comment]
好，我晚點確認一下發pr

**Comment by YCNeo** [comment]
測試完了，我改上去

SHA256 test:
password1: 0b14d501a594442a01c6859541bcb3e8164d183d32937b851835442f69d5c94e
password2: 6cf615d5bcaac778352a8f1f3360d23f02f34ec182e259897fd6ce485d7870d4
password3: 5906ac361a137e2d286465cd6588ebb5ac3f5ae955001100bc41577c3d751764
password4: b97873a40f73abedd8d685a7cd5e5f85e4a9cfb83eac26886640a0813850122b
password5: 8b2c86ea9cf2ea4eb517fd1e06b74f399e7fec0fef92e3b482a6cf2e2b092023
password6: 598a1a400c1dfdf36974e69d7e1bc98593f2e15015eed8e9b7e47a83b31693d5
password7: 5860836e8f13fc9837539a597d4086bfc0299e54ad92148d54538b5c3feefb7c
password8: 57f3ebab63f156fd8f776ba645a55d96360a15eeffc8b0e4afe4c05fa88219aa
password9: 9323dd6786ebcbf3ac87357cc78ba1abfda6cf5e55cd01097b90d4a286cac90e
password10: aa4a9ea03fcac15b5fc63c949ac34e7b0fd17906716ac3b8e58c599cdc5a52f0
